ExercicioAula01/Portal/Models/ConsultaPrecoPrazo.cs
namespace Portal.Models
{
    public class ConsultaPrecoPrazo
    {
        public int Id { get; set; }
        public string CdServico { get; set; }
        public string CepOrigem { get; set; }
        public string CepDestino { get; set; }
        public string VlPeso { get; set; }
        public int CdFormato { get; set; }
        public decimal VlComprimento { get; set; }
        public decimal VlAltura { get; set; }
        public decimal VlLargura { get; set; }
        public decimal VlDiametro { get; set; }
        public string CdMaoPropria { get; set; }
        public decimal VlValorDeclarado { get; set; }
        public string CdAvisoRecebimento { get; set; }
    }
}

ExercicioAula01/Portal/Controllers/ConsultaPrecoPrazoController.cs
using System.Web.Mvc;
using Portal.Correios.CalculoPrecoPrazo;
using Portal.Models;

namespace Portal.Controllers
{
    public class ConsultaPrecoPrazoController : Controller
    {
        private CalcPrecoPrazoWSSoapClient client;

        public ConsultaPrecoPrazoController()
        {
            client = new CalcPrecoPrazoWSSoapClient();
        }

        public ActionResult Index()
        {
            return View(new ConsultaPrecoPrazo());
        }

        public ActionResult Resultado(ConsultaPrecoPrazo consulta)
        {
            var resposta = client.CalcPrecoPrazo("", "", consulta.CdServico, consulta.CepOrigem, consulta.CepDestino,
                consulta.VlPeso, consulta.CdFormato, consulta.VlComprimento, consulta.VlAltura, consulta.VlLargura,
                consulta.VlDiametro, consulta.CdMaoPropria, consulta.VlValorDeclarado, consulta.CdAvisoRecebimento);

            return View(resposta.Servicos);
        }
    }
}

ExercicioAula01/Portal/Views/ConsultaPrecoPrazo/Index.cshtml
@model Portal.Models.ConsultaPrecoPrazo

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("Resultado", "ConsultaPrecoPrazo", FormMethod.Post)) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>ConsultaPrecoPrazo</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CdServico, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CdServico, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CdServico, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CepOrigem, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CepOrigem, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CepOrigem, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CepDestino, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CepDestino, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CepDestino, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.VlPeso, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VlPeso, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VlPeso, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CdFormato, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CdFormato, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CdFormato, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.VlComprimento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VlComprimento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VlComprimento, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.VlAltura, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VlAltura, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VlAltura, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.VlLargura, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VlLargura, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VlLargura, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.VlDiametro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VlDiametro, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VlDiametro, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CdMaoPropria, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CdMaoPropria, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CdMaoPropria, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.VlValorDeclarado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VlValorDeclarado, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VlValorDeclarado, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CdAvisoRecebimento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CdAvisoRecebimento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CdAvisoRecebimento, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Consultar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ExercicioAula01/Portal/Views/ConsultaPrecoPrazo/Resultado.cshtml
@model Portal.Correios.CalculoPrecoPrazo.cServico[]

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>ConsultaPrecoPrazo</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CdServico)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CdServico)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CepOrigem)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CepOrigem)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CepDestino)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CepDestino)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.VlPeso)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.VlPeso)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CdFormato)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CdFormato)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.VlComprimento)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.VlComprimento)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.VlAltura)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.VlAltura)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.VlLargura)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.VlLargura)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.VlDiametro)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.VlDiametro)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CdMaoPropria)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CdMaoPropria)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.VlValorDeclarado)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.VlValorDeclarado)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CdAvisoRecebimento)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CdAvisoRecebimento)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

ExercicioAula01/Portal/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Consulta Preço Prazo", "#", "#", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tissei</p>
        </footer>
    </div>

    @RenderSection("scripts", false)
</body>
</html>